<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style>@charset "utf-8";body{font-family:Roboto;margin:0;padding:0;color:#000}p{color:#000;font-size:16px;line-height:30px;font-weight:300}a{transition:.3s linear;text-decoration:none}a:focus,a:hover{text-decoration:none}li,ul{list-style:none;margin:0;padding:0}h1{margin-top:0}.main-wraper{width:50%;margin:0 auto}.wraper{width:100%;display:block;clear:both;height:60px}.left-div{width:15%;float:left;padding-top:15px;font-size:16px;padding-right:3px}.right-div{width:84%;float:left}.form1{margin:50px 0;font-size:14px}.form1 .form-control{display:block;width:100%;height:auto;padding:6px 12px;font-size:14px;line-height:1.42857143;color:#555;background-color:#fff;background-image:none;border:none;border-bottom:1px solid #000;border-radius:0;-webkit-box-shadow:none;box-shadow:none;-webkit-transition:border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;-o-transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s}input:focus-visible{outline:0!important;box-sizing:none!important}p{font-size:16px;line-height:26px}p a{font-size:16px;line-height:26px;font-weight:700;color:#4472c4;text-decoration:underline}p a:hover{color:red}h1{font-size:22px;line-height:26px;text-align:center;font-weight:700;margin-bottom:20px}h2{font-size:18px;line-height:26px;font-weight:700}h3{font-size:18px;line-height:26px;font-weight:700;color:red;font-style:italic}h4{font-size:20px;line-height:26px;font-weight:700;color:red;font-style:italic;margin:50px 0}ul li{font-size:16px;line-height:26px;padding-left:20px;margin-left:15px}ul.dot li{font-size:16px;line-height:26px;list-style:disc;padding-left:20px;margin:20px 0 20px 15px}ol li{font-size:12px;line-height:22px;list-style:decimal;padding-left:20px;margin:20px 0 20px 15px}.line{border-bottom:1px solid #000;width:250px;display:block}ul.abc li{font-size:16px;line-height:22px;list-style:lower-alpha;padding-left:10px;margin:20px 0 20px 60px}ul.arrow{position:relative;list-style:none}ul.arrow li{margin-bottom:20px}ul.arrow li::before{content:'⮚';position:absolute;left:0;font-size:26px}ul.center-list{text-align:center;margin:50px 0}ul.center-list li{list-style:none;display:inline-block;margin:0 40px;font-weight:700}.page-number{font-size:18px;line-height:26px;text-align:center;font-weight:700;margin:40px 0;padding:30px 0 10px 0}@media only screen and (max-width:1600px){.right-div{width:75%}.left-div{width:17%}}@media only screen and (max-width:1536px){.left-div{width:18%}}@media only screen and (max-width:1440px){.left-div{width:19%}}@media only screen and (max-width:1367px){.left-div{width:20%}}@media only screen and (max-width:1300px){.left-div{width:21%}}@media only screen and (max-width:1024px){.right-div{width:60%}.left-div{width:35%}}@media only screen and (max-width:767px){.right-div{width:50%}.left-div{width:48%}}</style>
</head>
<body>
<div class="main-wraper">
    <h1>Informativa di trattamento dei dati personali<sup>1</sup></h1>
    <p>La società Tekamed S.r.l., è tenuta a fornirLe, prima che i Suoi dati personali siano raccolti le seguenti informazioni, relative al loro trattamento da parte della nostra Società.</p>
    <h2>1. Soggetti del trattamento</h2>
    <p>Il paragrafo che segue illustra chi e con quale ruolo tratterà i dati personali degli interessati.<br>
        <strong>Il Titolare del trattamento dati è TEKAMED S.R.L.</strong>, (C.F.: 01997780380), con sede legale in Ferrara (FE), via Bellaria, 6 (più avanti anche la “Società”), in persona del legale rappresentante pro tempore, al quale l'interessato potrà rivolgersi per ottenere qualsiasi ulteriore informazione connessa con la presente informativa ed eventualmente esercitare i diritti che la Legge gli riconosce – così come descritti nel testo che segue – anche scrivendo all’indirizzo di posta elettronica <strong>info@tekamed.it</strong><br>
        Le ricordiamo, inoltre, che Il Responsabile per la <strong>Protezione dei Dati</strong> designato per Tekamed S.r.l. è l’Avv. Donato La Muscatella, contattabile presso la sede legale o all’indirizzo di posta elettronica <strong>dpo@tekamed.it</strong><br>
    </p>
    <h2>2. Fonte e categoria dei dati personali</h2>

    <p>Il paragrafo che segue illustra in che modo saranno acquisiti i Suoi dati personali.<br>
        La legge definisce “dato personale” qualunque informazione relativa a persona fisica, identificata o identificabile, anche indirettamente, mediante riferimento a qualsiasi altra informazione, ivi compreso un numero di identificazione personale<sup>2</sup>. Lo sono, in altre parole, le informazioni (ad esempio, il nome o il cognome) che identificano o rendono identificabile una persona e che possono fornire dettagli sulle sue caratteristiche, le sue abitudini, il suo stile di vita, le sue relazioni personali, il suo stato di salute, la sua situazione economica e così via.<br>
        I dati personali in nostro possesso sono raccolti di direttamente presso gli interessati e consistono in dati identificativi e di contatto.<br>
        Tutti i dati personali vengono trattati nel rispetto di ogni disposizione di legge applicabile, valutando tutti i rischi connessi e rispettando gli obblighi di riservatezza cui si è sempre ispirata l'attività della nostra Azienda. </p>
    <h2>3. Finalità del trattamento e base giuridica</h2>
    <p>Il paragrafo che segue illustra per quali ragioni saranno trattati i Suoi dati personali.</p>
    <div class="line"></div>
    <ol>
        <li>Nota informativa di trattamento e dichiarazione di consenso ai sensi del Decreto Legislativo 30 giugno 2003, n. 196 “Codice in materia di protezione dei dati personali” e successive modificazioni e integrazioni (con particolare riguardo al Decreto Legislativo 10 agosto 2018, n. 101) e Regolamento U.E. n. 679 del Parlamento Europeo e del Consiglio del 27/4/2016, relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali.</li>
        <li>Più in dettaglio, ai sensi dell’art 4, paragrafo primo, n. 1, Regolamento U.E. n. 679/2016: “qualsiasi informazione riguardante una persona fisica identificata o identificabile («interessato»); si considera identificabile la persona fisica che può essere identificata, direttamente o indirettamente, con particolare riferimento a un identificativo come il nome, un numero di identificazione, dati relativi all'ubicazione, un identificativo online o a uno o più elementi caratteristici della sua identità fisica, fisiologica, genetica, psichica, economica, culturale o sociale”.</li>
    </ol>
    <div class="page-number">1</div>
</div>
</body>
</html>