<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style>@charset "utf-8";body{font-family:Roboto;margin:0;padding:0;color:#000}p{color:#000;font-size:16px;line-height:30px;font-weight:300}a{transition:.3s linear;text-decoration:none}a:focus,a:hover{text-decoration:none}li,ul{list-style:none;margin:0;padding:0}h1{margin-top:0}.main-wraper{width:50%;margin:0 auto}.wraper{width:100%;display:block;clear:both;height:60px}.left-div{width:15%;float:left;padding-top:15px;font-size:16px;padding-right:3px}.right-div{width:84%;float:left}.form1{margin:50px 0;font-size:14px}.form1 .form-control{display:block;width:100%;height:auto;padding:6px 12px;font-size:14px;line-height:1.42857143;color:#555;background-color:#fff;background-image:none;border:none;border-bottom:1px solid #000;border-radius:0;-webkit-box-shadow:none;box-shadow:none;-webkit-transition:border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;-o-transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s}input:focus-visible{outline:0!important;box-sizing:none!important}p{font-size:16px;line-height:26px}p a{font-size:16px;line-height:26px;font-weight:700;color:#4472c4;text-decoration:underline}p a:hover{color:red}h1{font-size:22px;line-height:26px;text-align:center;font-weight:700;margin-bottom:20px}h2{font-size:18px;line-height:26px;font-weight:700}h3{font-size:18px;line-height:26px;font-weight:700;color:red;font-style:italic}h4{font-size:20px;line-height:26px;font-weight:700;color:red;font-style:italic;margin:50px 0}ul li{font-size:16px;line-height:26px;padding-left:20px;margin-left:15px}ul.dot li{font-size:16px;line-height:26px;list-style:disc;padding-left:20px;margin:20px 0 20px 15px}ol li{font-size:12px;line-height:22px;list-style:decimal;padding-left:20px;margin:20px 0 20px 15px}.line{border-bottom:1px solid #000;width:250px;display:block}ul.abc li{font-size:16px;line-height:22px;list-style:lower-alpha;padding-left:10px;margin:20px 0 20px 60px}ul.arrow{position:relative;list-style:none}ul.arrow li{margin-bottom:20px}ul.arrow li::before{content:'⮚';position:absolute;left:0;font-size:26px}ul.center-list{text-align:center;margin:50px 0}ul.center-list li{list-style:none;display:inline-block;margin:0 40px;font-weight:700}.page-number{font-size:18px;line-height:26px;text-align:center;font-weight:700;margin:40px 0;padding:30px 0 10px 0}@media only screen and (max-width:1600px){.right-div{width:75%}.left-div{width:17%}}@media only screen and (max-width:1536px){.left-div{width:18%}}@media only screen and (max-width:1440px){.left-div{width:19%}}@media only screen and (max-width:1367px){.left-div{width:20%}}@media only screen and (max-width:1300px){.left-div{width:21%}}@media only screen and (max-width:1024px){.right-div{width:60%}.left-div{width:35%}}@media only screen and (max-width:767px){.right-div{width:50%}.left-div{width:48%}}</style>
</head>
<body>
<div class="main-wraper">
    <p>I punti seguenti illustrano i diritti che potrà esercitare, in qualità di interessato, in relazione al trattamento dei Suoi dati personali:</p>
    <ul class="arrow">
        <li>ha diritto in qualunque momento di ottenere la conferma dell'esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile;</li>
        <li>ha diritto, inoltre, di ottenere l’indicazione: a) dell’origine dei dati personali; b) delle finalità e modalità del trattamento; c) della logica applicata in caso di trattamento effettuato con l’ausilio di strumenti elettronici; d) degli estremi identificativi del Titolare, dei responsabili e del rappresentante designato ai sensi dell’articolo 5, comma secondo; e) dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualità di rappresentante designato nel territorio dello Stato, di responsabili o autorizzati;</li>
        <li>ha diritto, altresì, di: a) ottenere l'aggiornamento, la rettificazione ovvero, quando vi ha interesse, l'integrazione dei dati; b) ottenere la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non è necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati; c) ottenere l'attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza, anche per quanto riguarda il loro contenuto, di coloro ai quali i dati sono stati comunicati o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un impiego di mezzi manifestamente sproporzionato rispetto al diritto tutelato; d) in presenza di condizioni specificamente previste dalle legge, di ricevere in un formato strutturato, di uso comune e leggibile da dispositivo automatico i dati personali che lo riguardano forniti a un Titolare del trattamento e ha il diritto di trasmettere tali dati a un altro Titolare del trattamento senza impedimenti da parte del Titolare del trattamento cui li ha forniti, anche mediante trasmissione diretta (cosiddetto diritto alla portabilità dei dati); e) proporre reclamo al Garante per la Protezione dei Dati Personali in Roma;</li>
        <li>ha infine diritto di opporsi, in tutto o in parte: a) per motivi legittimi al trattamento dei dati personali che lo riguardano, ancorché pertinenti allo scopo della raccolta; b) al trattamento di dati personali che lo riguardano a fini di invio di materiale pubblicitario o di vendita diretta o per il compimento di ricerche di mercato o di comunicazione commerciale.</li>
    </ul>
    <p>Tali diritti potranno essere esercitati rivolgendosi al Titolare di trattamento, scrivendo agli indirizzi sopra indicati.<br>
        <br>
        Il Titolare del trattamento si riserva il diritto di apportare modifiche alle presenti politiche di trattamento dei dati personali in qualunque momento, dandone comunicazione agli interessati e richiedendo eventuali consensi ulteriori che si rendano necessari, previa lettura dell’informativa aggiornata, prima di proseguire con il trattamento.</p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="page-number">4</div>
</div>
</body>
</html>